[[libposit]]
arch = "aarch64"
git-tree-sha1 = "ecf645846290e11a0f1ad14ed6b55532fbba18c7"
os = "macos"

    [[libposit.download]]
    sha256 = "1e4df5ee9a20c26fb48ed7ae669f07c671552ca39c92084e74b3a2db809ec2ac"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.aarch64-apple-darwin.tar.gz"
[[libposit]]
arch = "aarch64"
git-tree-sha1 = "f1fa2141207036ed8b9daeb6e868f52f0f8d6aee"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "09c2a498e13b0aab9459130570a8ea9a4423a2603e2e58e9ae846b81b6ebcef6"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.aarch64-linux-gnu.tar.gz"
[[libposit]]
arch = "aarch64"
git-tree-sha1 = "086610b06a4a5f85a0247600bfc8bc0798018f3b"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "be5305bcfef7c9342c204603d8367a54b5e31904a7b250c738952c947f512997"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.aarch64-linux-musl.tar.gz"
[[libposit]]
arch = "aarch64"
git-tree-sha1 = "c4b8e589879fb8ee216ef67ebd5f70424490e120"
os = "freebsd"

    [[libposit.download]]
    sha256 = "785bd944006cbf2173acb6d17ffe926b4f8c1a7643c36128d4a390a992cc0666"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.aarch64-unknown-freebsd.tar.gz"
[[libposit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cad75ce5f490acb12ca2ad4723c936cdf6093cdf"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "2b97d667f8e0c078d66c8251a7eb5d259399d49b34e049e200eafd143fb1e999"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.armv6l-linux-gnueabihf.tar.gz"
[[libposit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d09b1ef0b166b054d4369559860d6521c4486bee"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "3e2f2259601877efb6c02385bcd4251d79e3b26ff4e9fac5ede2bdaab3d39775"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.armv6l-linux-musleabihf.tar.gz"
[[libposit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4dd8b8b38f28b9c9e6d8c1c3ca2e16f091e9cf55"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "694931fc712418e2aa536227bfb59a257de32540237fe65d5feb0b51396821ec"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.armv7l-linux-gnueabihf.tar.gz"
[[libposit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2e704f0d5080b4d4bf09ef9ac503beaf25db9ac"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "051fe237819ed76f67a9d77afa7927eaf413bcd89c2611f49b6698a71339c916"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.armv7l-linux-musleabihf.tar.gz"
[[libposit]]
arch = "i686"
git-tree-sha1 = "7b454424bcd0898f2d9f218f71c264752615ac45"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "1d08a0bc5ab1e54a0317faba1e0e38501cf4f1c540fe29180d23bd2c5a1a8892"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.i686-linux-gnu.tar.gz"
[[libposit]]
arch = "i686"
git-tree-sha1 = "ba6e256da0a6db5140b96b05a64fcad70b842cbd"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "0f132af8cabc1ee2e0a57b45b807c1d15ac409bbbce9619b29bb89ce9f201388"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.i686-linux-musl.tar.gz"
[[libposit]]
arch = "i686"
git-tree-sha1 = "55bf286863b91e1f91363311a28aa791cace5fc4"
os = "windows"

    [[libposit.download]]
    sha256 = "bbadd33978a322508a73a9aa7a149f9b2b1efb319e44591a1cb00b17cbccdedb"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.i686-w64-mingw32.tar.gz"
[[libposit]]
arch = "powerpc64le"
git-tree-sha1 = "05c7ca896eed38497ebf08342ab283b2ccffe58f"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "80674d66d073d007a33ed67672c1c716a8c1bedb6df09cc2ddc85a2bfdda8777"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.powerpc64le-linux-gnu.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "3011d11e2f740d92c088175afae9caecbe6713f1"
os = "macos"

    [[libposit.download]]
    sha256 = "d0c02738f67b822679b5bf87cab07f05083f9b3b5946f646eefd29634895df22"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.x86_64-apple-darwin.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "38549985b779369c440db9661d2c4a95187cdd1d"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "670adb0628a722cd5a2b90d9d4cd504555e3ea35e0bdcce5df42ff0b1558b832"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.x86_64-linux-gnu.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "0c6894428337cb889dc7e300a65218cb279cfa02"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "6ce27d28e978bd4ba4f261c3f7c69e86cbc40edf13a31924a263f593433a0d2e"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.x86_64-linux-musl.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "d9ad54e4b948d6ddd1ac333a903a016a1db0cb88"
os = "freebsd"

    [[libposit.download]]
    sha256 = "9de600ba6f9e05201c1f27d915659f6b936093f6507c3a26ad77af3acb889a48"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.x86_64-unknown-freebsd.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "de33076c65fbae0d5f6f49c9bd088a3921c217dd"
os = "windows"

    [[libposit.download]]
    sha256 = "cf04d1ae8751403a55a5d31ac91996fe240cf0cadb37046c99cd71646447b1f0"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.0+0/libposit.v1.0.0.x86_64-w64-mingw32.tar.gz"
