[[libposit]]
arch = "aarch64"
git-tree-sha1 = "3c72be325117d3ce956ddab31362cf7d0624af61"
os = "macos"

    [[libposit.download]]
    sha256 = "97ac1796ea1a811b98f3b3f190057c3e18825fb0eedae7e28cd5e38440a4e127"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.aarch64-apple-darwin.tar.gz"
[[libposit]]
arch = "aarch64"
git-tree-sha1 = "64ffaf7f8d784d473656121d72535cdea8b44f41"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "24f44a4b225ced0f66fcffd2b62bfd475ec8debcdaf48bcf506af58ceb914d38"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.aarch64-linux-gnu.tar.gz"
[[libposit]]
arch = "aarch64"
git-tree-sha1 = "5b7cfd9fb9849caeb95e104d1de243d1a9c497e0"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "290cd5e57bde09ab87b5aec69ad3c9ec03ad234524b6b3c46d02ac3f5f7ab403"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.aarch64-linux-musl.tar.gz"
[[libposit]]
arch = "aarch64"
git-tree-sha1 = "157533c1692ffbcc9b86419ec2c3fb6662263056"
os = "freebsd"

    [[libposit.download]]
    sha256 = "6a0468383a96f47cfaeebccd8b532b8e2930cf53952c88d6d1b02ea7196db804"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.aarch64-unknown-freebsd.tar.gz"
[[libposit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2a5dbb2caccb326916186b16fb3dd4716feca333"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "b6ca6ff350ee6563c1f0168827f28bf2aed31c213d0bf761841320c7f2f31a68"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.armv6l-linux-gnueabihf.tar.gz"
[[libposit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e6a79a56fa06c7f05c11b632bbbd7e6fe0d3c22"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "f2a3c575225183ae3b4f5603f4b3182114e2b0f6bfcb7f41bc31b4824d7e48e6"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.armv6l-linux-musleabihf.tar.gz"
[[libposit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e67067b691807468e1ac427383e8c8aa4badee0d"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "132651aec60811f5966f18d22964a2f6721cd1b2fa37e7b36fd1a256ace9c98c"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.armv7l-linux-gnueabihf.tar.gz"
[[libposit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "77b03dfa337b81042ec9022efb7b9bfbea42a58b"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "a7f425c7315209aa6c1f4f03d08d8337ecf97be985d8864b044b02e3b16637a0"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.armv7l-linux-musleabihf.tar.gz"
[[libposit]]
arch = "i686"
git-tree-sha1 = "6d4110df230d6de445b7e046a204aac9be4dda9d"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "d3a57443e5b7a408a2b92d99bf5927de70ce0825dc3ff68eda4c58a714ac9d43"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.i686-linux-gnu.tar.gz"
[[libposit]]
arch = "i686"
git-tree-sha1 = "d52a72ab8052c5afcd283a32a694d3749d43167f"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "3156e88170d414a57547a85479c9b609de983058d117c4f84b605073835418ce"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.i686-linux-musl.tar.gz"
[[libposit]]
arch = "i686"
git-tree-sha1 = "94287684d366019c05b0542875a47c74d68e78b6"
os = "windows"

    [[libposit.download]]
    sha256 = "b3d82759a26699ab8ea1a56c66ba65c11d18d64bfb8ef80b426e3f0a00ea49f3"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.i686-w64-mingw32.tar.gz"
[[libposit]]
arch = "powerpc64le"
git-tree-sha1 = "39531d1cd50e2379faf54a4fbb6d181dbc58388b"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "3caa469cc7668cbd4c3ead850020d391e7063ac1a67c0fd5521c898375d7e6ac"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.powerpc64le-linux-gnu.tar.gz"
[[libposit]]
arch = "riscv64"
git-tree-sha1 = "a58d86d9abadf44f1e4ac68ba729d6565d565460"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "fab861d2f827069e6b64003908d217594d63ba203bf9db2de405c0b6868a9f88"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.riscv64-linux-gnu.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "50bbba0c88b26b52905f6d2adcec07292b55f91c"
os = "macos"

    [[libposit.download]]
    sha256 = "321d761c4b11a51972cb71ffd69b3232ed0006e04923b7717fe19b9524a0af52"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.x86_64-apple-darwin.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "348617ed1884b50ec624cba5585196fbab58e1de"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "d8eba63f86474beb40abe7ecd4db7290662bcea8ad706f1cf8697803210fac3a"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.x86_64-linux-gnu.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "8b18e27ee120e64a1107940ea526e11bcf631402"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "00fc52779fdf158225fbc1a964f53ea7d071a18e4733172fb410a991ac570524"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.x86_64-linux-musl.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "b8d73f75ebc551a5cc09efe15d41bb0b3f8f84c8"
os = "freebsd"

    [[libposit.download]]
    sha256 = "4a2cdeb5d03ac4fad49471658dd99cb2f04672727aed61125809512835026380"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.x86_64-unknown-freebsd.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "73e7f27d740a50b06aaf84d12901a6b98ca21aec"
os = "windows"

    [[libposit.download]]
    sha256 = "064ab7a49389766609c504d4d8baaed95a652cffec6718d7f7f8edfdd548832a"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.2+0/libposit.v1.0.2.x86_64-w64-mingw32.tar.gz"
