[[libposit]]
arch = "aarch64"
git-tree-sha1 = "69bf1a468d799dc1c82fe9c710a88bfd1b466fe5"
os = "macos"

    [[libposit.download]]
    sha256 = "454e45846ba95001a753a3c7a90b59a7dc1cf9ce6c3d0dd16f11f906659294ef"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.aarch64-apple-darwin.tar.gz"
[[libposit]]
arch = "aarch64"
git-tree-sha1 = "f24a945360fafbbc63df66e4601aa12122dc9887"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "34e237b9591ddc26b9eca082d0a97e18c5e1c92b082b5488333fe08d6cc4ddac"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.aarch64-linux-gnu.tar.gz"
[[libposit]]
arch = "aarch64"
git-tree-sha1 = "5cabded1f7e844adf3c94c1e0b5104d04e9519da"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "ad3ad4e5528871aa30fe945ba3abe36d3ec6169a5cd28e7d582320b2b70c6e9c"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.aarch64-linux-musl.tar.gz"
[[libposit]]
arch = "aarch64"
git-tree-sha1 = "b2ce74527b8578abb41a5c8688898e4837e56f04"
os = "freebsd"

    [[libposit.download]]
    sha256 = "3cebb362c81fc86c493f09cb9cd8a67c5c747a5e0be7560a58051ef868b8edc8"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.aarch64-unknown-freebsd.tar.gz"
[[libposit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2a0206421fed911111f661941caab254becab6f2"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "0e95dfbdf811685cdccc038b959145e26cd042fdc82ecac680c374acfa57fce3"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.armv6l-linux-gnueabihf.tar.gz"
[[libposit]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a8359eb49c113825e476bc7ef999633586f66a21"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "f56fa50b4887da54a7d6c22afb62387e2cb58be84e62b7aa7c11eafccd91eed0"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.armv6l-linux-musleabihf.tar.gz"
[[libposit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8fb75656505bf670eb44ea8b4b1c84e1fc3ce46b"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "6b29c0ede537dbf6e0338f35221dbc896c54f99b38b85c044bee9b2bd4e94b1e"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.armv7l-linux-gnueabihf.tar.gz"
[[libposit]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c8bdcd1cc7dae2765179c83f9b5d427fa928796f"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "3fe0c623b182652846989462ffc5e31d6a56dd30df68b06fb3cd20abe5db1f06"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.armv7l-linux-musleabihf.tar.gz"
[[libposit]]
arch = "i686"
git-tree-sha1 = "dfe2138391566bb5fc7af3fcb92b1b424333a852"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "6c3123392331f68854260f412750ca8c46ee931d39f908e714d6cd516039d10a"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.i686-linux-gnu.tar.gz"
[[libposit]]
arch = "i686"
git-tree-sha1 = "c87e307869e8a32595ad514a01cfc1db7254bd37"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "71485e0c06d679986174621d89ec6481c3c8ecffe29dffc262988f98df5db66f"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.i686-linux-musl.tar.gz"
[[libposit]]
arch = "i686"
git-tree-sha1 = "5f59ce45d788ff31afd66578b3018fb094719884"
os = "windows"

    [[libposit.download]]
    sha256 = "dad562370cf2e72896f5e1db2feebfb90d6a5e74ad41519289b02df046add5f6"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.i686-w64-mingw32.tar.gz"
[[libposit]]
arch = "powerpc64le"
git-tree-sha1 = "90f83caa8ec05584a4d3b0e9e4d8b23265c156e2"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "b3bf74cbfea72471ea95183f104f8be8d3d4388a8a191f29f1ab3217fd5c53c5"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.powerpc64le-linux-gnu.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "e20aad2017f0c73de345012df9d9f11060e886d6"
os = "macos"

    [[libposit.download]]
    sha256 = "89a097a68a5bf1a6f7b08818b53ba9b4b60b5ccd398e424ef5ab088d8dd7d517"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.x86_64-apple-darwin.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "3d8dcf583aac7c379bb64bb5e1a7b8f677b3388f"
libc = "glibc"
os = "linux"

    [[libposit.download]]
    sha256 = "a4a4c67638ba73de9b28955d778e23dae1f7118f2b1f1df280970fed9eb3af3c"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.x86_64-linux-gnu.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "e1998b1d888c54cee3529f62d477aacd06360261"
libc = "musl"
os = "linux"

    [[libposit.download]]
    sha256 = "6ea9a96f8e08429c22c00902158225b3630f76875ad409f458faedb1c179d3c8"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.x86_64-linux-musl.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "b4b9035117f5618d6c7bbf746c66e0e7bb145421"
os = "freebsd"

    [[libposit.download]]
    sha256 = "26e04b136ca58597fecca1c262f3e82f82c2459970e055d90e2843d198f027a8"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.x86_64-unknown-freebsd.tar.gz"
[[libposit]]
arch = "x86_64"
git-tree-sha1 = "dab3eaa7e0c0c9c5b19dd343ce6e05fb9e689b75"
os = "windows"

    [[libposit.download]]
    sha256 = "2148dc9df053c298a12077aba092c7358f83712ff2e1e97f75e833a05ddec41c"
    url = "https://github.com/JuliaBinaryWrappers/libposit_jll.jl/releases/download/libposit-v1.0.1+0/libposit.v1.0.1.x86_64-w64-mingw32.tar.gz"
