# Autogenerated wrapper script for libposit_jll for aarch64-apple-darwin
export libposit

JLLWrappers.@generate_wrapper_header("libposit")
JLLWrappers.@declare_library_product(libposit, "@rpath/libposit.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libposit,
        "lib/libposit.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
